### ISSUE TITLE
How to set sprite url of background-image attribute?

### ISSUE THREAD

**Issue by ilterra** [jkphl/grunt-iconizr#19]
Hi,
is there the possibility to set the url of the sprite in the background-image attribute?

Example, with these settings:

``` javascript
iconizr: {
    options: {
        common: "icon",
        spritedir: '.',
        render: {
            css: false,
            scss: '../scss/sprite/_sprite'
        }
    },
    sprite: {
        src: 'svg',
        dest: 'img'
    }
}
```

I get:

``` css
.icon {
    background-image: url(icons.svg);
}
```

But I'd rather have:

``` css
.icon {
    background-image: url(../img/icons.svg);
}
```

Since the scss partial is compiled in an app.css in a css folder.

Thanks,
Alberto
