### ISSUE TITLE
The SASS render option doesn't use the sprite

### ISSUE THREAD

**Issue by nandastone** [jkphl/grunt-iconizr#6]
When using the SASS renderer, the output _.scss_ file doesn't actually use the spritesheet:

```
iconizr:
    dist:
        src: ['src/img/test/']
        dest: '<%= pkg.deployPath %>/img/svg/'
        options:
            level: 0
            verbose: 1
            prefix: 'icon'
            render:
                css: false
                scss: '_icons'
```

__icons-svg-sprite.scss:_

```
.icon-arrow-black {
    background-position: 0 0;
    @extend %icon;
    # data URIs instead of spritesheet reference
    background-image: url("data:image/svg+xml,%3Csvg%20xmlns%3D%22h<etc>");
}

# etc
```

Is this intended?
