### ISSUE TITLE
Image dimensions without additional class

### ISSUE THREAD

**Issue by thulstrup** [jkphl/grunt-iconizr#7]
Is there a way to get the image dimensions without having to add an additional class to the markup?

At the moment the css looks like this (with dims set to true):

``` css
.icon-star { 
  background-position: 0 0;
  background-repeat: no-repeat;
  background-image: url(icons/icons.svg);
}

.icon-star-dims {
  width: 32px;
  height: 32px;
}
```

What I would like is this:

``` css
.icon-star { 
  background-position: 0 0;
  background-repeat: no-repeat;
  background-image: url(icons/icons.svg);
  width: 32px;
  height: 32px;
}
```
